### PR TITLE
Fix make demo independent

### PR DESCRIPTION
**Pull request by rdkmaster**

### CODE REVIEW

**Comment by rdkmaster** [comment]
dialog/popup-option 错误

image

**Comment by rdkmaster** [comment]
image

**Comment by rdkmaster** [comment]
凡是涉及到滚动条的，都有下面的问题

image

**Comment by rdkmaster** [comment]
graph/resize

image

**Comment by rdkmaster** [comment]
i18n/full

image

**Comment by rdkmaster** [comment]
loading/ball

image

**Comment by rdkmaster** [comment]
loading/full

image

**Comment by rdkmaster** [comment]
loading/user-defined

aa

**Comment by hpyou** [comment]
滚动条的问题，路径改下
image

**Comment by rdkmaster** [comment]
misc/zone-for-performance  拖动方框的时候出现

image

**Comment by rdkmaster** [comment]
tab/api

image

**Comment by rdkmaster** [comment]
tab/basic  样式问题

image

**Comment by rdkmaster** [comment]
泳道图，也是样式问题，plunker上无法解释scss导致的

image

**Pull request merged**
